task_name = "train"
task_type="transcribe"

[data]
data_name = "mozilla-foundation/common_voice_17_0"
language = "hi"
streaming = true
no_of_test_samples = 200

[model]
model_name = "openai/whisper-base"
language = "Hindi"

[paths]
model_save_path = "checkpoints"

[logger]
environment="dev"

[training]
per_device_train_batch_size = 16
gradient_accumulation_steps = 1
learning_rate = 1e-5
warmup_steps = 500
max_steps = 9000
gradient_checkpointing=true
fp16=true
evaluation_strategy="steps"
per_device_eval_batch_size=8
predict_with_generate=true
generation_max_length=225
save_steps=500
eval_steps=500
logging_steps=100
report_to="tensorboard"
load_best_model_at_end=true
metric_for_best_model="wer"
greater_is_better=false
push_to_hub=false